version: "2"

services:
  whmcs_mysql:
    image: mysql/mysql-server:5.7
    container_name: "whmcs_mysql"
    hostname: whmcs_mysql
    restart: always
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      whmcs:
        ipv4_address: 172.18.18.2
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_ROOT_HOST: '%'
      SMTP_HOST: 172.18.18.4
      SMTP_PORT: 1025
    ports:
      - 3308:3306

  whmcs_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'whmcs_phpmyadmin'
    links:
      - whmcs_mysql
    environment:
      PMA_HOST: 172.18.18.2
      PMA_PORT: 3306
    ports:
      - '8083:80'
    networks:
      whmcs:
        ipv4_address: 172.18.18.5

  whmcs_web:
    image: fauzie/docker-whmcs:latest
    container_name: "whmcs_web"
    hostname: whmcs_web
    networks:
      whmcs:
        ipv4_address: 172.18.18.3
    restart: always
    depends_on:
      - whmcs_mysql
    environment:
      WORKER_PROCESSES: 4
      VIRTUAL_HOST: whmcs.local
      PHP_VHOST: whmcs.local
      APP_PASSWORD: secret
      WHMCS_SERVER_IP: 172.18.18.1
      HTTPS: "on"
      TZ: "Europe/Paris"
    ports:
      - 8082:80
      - 2222:2222
    volumes:
      - ./www:/var/www/whmcs
      - ./logs/nginx:/var/log/nginx

  whmcs_mailhog:
    image: mailhog/mailhog
    container_name: "whmcs_mailhog"
    hostname: whmcs_mailhog
    restart: always
    networks:
      whmcs:
        ipv4_address: 172.18.18.4
    ports:
      - 8025:8025
      - 1025:1025

networks:
  whmcs:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.18.0/29
          gateway: 172.18.18.1
